export type MaterialOMType = {
  cmdo_ods: string;
  rm: string;
  de: string;
  bda: string;
  om: string;
  cidade: string;
  estado: string;
  equipamento: string;
  modelo: string;
  fabricante: string;
  pn: string;
  sn: string;
  disponibilidade: string;
  motivoindisp: string;
  tipo_eqp: string;
  subsistema: string;
  grupo: string;
  latitude: string;
  longitude: string;
};
